services:
  - type: web
    name: trmarket-api
    env: node
    plan: free
    rootDir: trmarketapili/realtime-collector
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TVAPI_MARKET
        value: turkey
      - key: TVAPI_INTERVAL
        value: 5000
      - key: TRADINGVIEW_SESSION_ID
        fromSecret: true
